### ISSUE TITLE
Better Pattern Matching

### ISSUE THREAD

**Issue by TigranOhanyan** [amuradyan/fpscala#2]
https://github.com/amuradyan/fpscala/blob/f3c6abaaa4889652675362c787cf791b69efda19/src/main/scala/strictness_and_laziness/Strim.scala#L66

`if` condition can be on the left side of the arrow

**Comment by amuradyan** [comment]
@TigranOhanyan thanks a lot. 

I found a similar issue in the `Opshn` and tried to fix them both in #3

**Comment by amuradyan** [comment]
see #3
